package NewLanguage.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import java.util.Map;
import jetbrains.mps.smodel.runtime.PropertyConstraintsDescriptor;
import java.util.HashMap;
import jetbrains.mps.smodel.runtime.base.BasePropertyConstraintsDescriptor;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;

public class ArduinoBoard_Constraints extends BaseConstraintsDescriptor {
  public ArduinoBoard_Constraints() {
    super("NewLanguage.structure.ArduinoBoard");
  }

  @Override
  protected Map<String, PropertyConstraintsDescriptor> getNotDefaultProperties() {
    Map<String, PropertyConstraintsDescriptor> properties = new HashMap();
    properties.put("frequency", new BasePropertyConstraintsDescriptor("frequency", this) {
      @Override
      public boolean hasOwnValidator() {
        return true;
      }

      @Override
      public boolean validateValue(SNode node, String propertyValue) {
        String propertyName = "frequency";
        return Float.parseFloat((SPropertyOperations.getString(propertyValue))) >= 0 && Float.parseFloat((SPropertyOperations.getString(propertyValue))) < 1;
      }
    });
    return properties;
  }
}
