package NewLanguage.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import java.util.Map;
import jetbrains.mps.smodel.runtime.PropertyConstraintsDescriptor;
import java.util.HashMap;
import jetbrains.mps.smodel.runtime.base.BasePropertyConstraintsDescriptor;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;

public class Joystick_Constraints extends BaseConstraintsDescriptor {
  public Joystick_Constraints() {
    super("NewLanguage.structure.Joystick");
  }

  @Override
  protected Map<String, PropertyConstraintsDescriptor> getNotDefaultProperties() {
    Map<String, PropertyConstraintsDescriptor> properties = new HashMap();
    properties.put("xAxisPin", new BasePropertyConstraintsDescriptor("xAxisPin", this) {
      @Override
      public boolean hasOwnValidator() {
        return true;
      }

      @Override
      public boolean validateValue(SNode node, String propertyValue) {
        String propertyName = "xAxisPin";
        return (SPropertyOperations.getInteger(propertyValue)) >= 0 && (SPropertyOperations.getInteger(propertyValue)) <= 5;
      }
    });
    properties.put("yAxisPin", new BasePropertyConstraintsDescriptor("yAxisPin", this) {
      @Override
      public boolean hasOwnValidator() {
        return true;
      }

      @Override
      public boolean validateValue(SNode node, String propertyValue) {
        String propertyName = "yAxisPin";
        return (SPropertyOperations.getInteger(propertyValue)) >= 0 && (SPropertyOperations.getInteger(propertyValue)) <= 5;
      }
    });
    properties.put("pinNumber", new BasePropertyConstraintsDescriptor("pinNumber", this) {
      @Override
      public boolean hasOwnValidator() {
        return true;
      }

      @Override
      public boolean validateValue(SNode node, String propertyValue) {
        String propertyName = "pinNumber";
        return (SPropertyOperations.getInteger(propertyValue)) >= 8 && (SPropertyOperations.getInteger(propertyValue)) <= 13;
      }
    });
    return properties;
  }
}
