package NewLanguage.generator.template.main;

/*Generated by MPS */

import jetbrains.mps.generator.runtime.Generated;
import jetbrains.mps.generator.template.PropertyMacroContext;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.generator.template.SourceSubstituteMacroNodesContext;

@Generated
public class QueriesGenerated {
  public final boolean NEEDS_OPCONTEXT = false;

  public static Object propertyMacro_GetPropertyValue_3334193164822695678(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), "name");
  }

  public static Object propertyMacro_GetPropertyValue_3334193164822796939(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), "type");
  }

  public static Object propertyMacro_GetPropertyValue_6096292100219595790(final PropertyMacroContext _context) {
    return SPropertyOperations.getInteger(_context.getNode(), "xAxisPin") + "";
  }

  public static Object propertyMacro_GetPropertyValue_8766321956513475677(final PropertyMacroContext _context) {
    return !(SPropertyOperations.getString(_context.getNode(), "frequency").equals("0")) && !(SPropertyOperations.getString(_context.getNode(), "frequency").equals(""));
  }

  public static Object propertyMacro_GetPropertyValue_8766321956510851994(final PropertyMacroContext _context) {
    // <node> 
    if (Float.valueOf(SPropertyOperations.getString(_context.getNode(), "frequency")) >= 1) {
      return "";
    }
    return SPropertyOperations.getString(_context.getNode(), "frequency") + "";
  }

  public static Object propertyMacro_GetPropertyValue_8766321956509142112(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SNodeOperations.getConceptDeclaration(_context.getNode()), "name");
  }

  public static Object propertyMacro_GetPropertyValue_8766321956508669607(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), "type");
  }

  public static Object propertyMacro_GetPropertyValue_8766321956508684492(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SNodeOperations.getConceptDeclaration(_context.getNode()), "name");
  }

  public static Object propertyMacro_GetPropertyValue_8766321956508693981(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), "type");
  }

  public static Object propertyMacro_GetPropertyValue_8766321956508713498(final PropertyMacroContext _context) {
    return SPropertyOperations.getInteger(_context.getNode(), "pinNumber") + "";
  }

  public static Object propertyMacro_GetPropertyValue_6096292100218930034(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SNodeOperations.getConceptDeclaration(_context.getNode()), "name");
  }

  public static Object propertyMacro_GetPropertyValue_6096292100218703710(final PropertyMacroContext _context) {
    // <node> 
    if (SPropertyOperations.getString(SNodeOperations.getConceptDeclaration(_context.getNode()), "name").equals("Joystick")) {
      return SPropertyOperations.getInteger((SNodeOperations.cast(_context.getNode(), "NewLanguage.structure.Joystick")), "xAxisPin") + "";
    }
    return "";
  }

  public static Object propertyMacro_GetPropertyValue_6096292100218754513(final PropertyMacroContext _context) {
    if (SPropertyOperations.getString(SNodeOperations.getConceptDeclaration(_context.getNode()), "name").equals("Joystick")) {
      return SPropertyOperations.getInteger((SNodeOperations.cast(_context.getNode(), "NewLanguage.structure.Joystick")), "yAxisPin") + "";
    }
    return "";
  }

  public static Object propertyMacro_GetPropertyValue_6096292100218669808(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SNodeOperations.getConceptDeclaration(_context.getNode()), "name").equals("Joystick");
  }

  public static Object propertyMacro_GetPropertyValue_8766321956509269195(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), "type");
  }

  public static Object propertyMacro_GetPropertyValue_8766321956511159750(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), "name");
  }

  public static Object propertyMacro_GetPropertyValue_6096292100214891989(final PropertyMacroContext _context) {
    if (SPropertyOperations.getBoolean(SLinkOperations.getTarget(_context.getNode(), "loop", true), "value")) {
      return "true";
    }
    return "false";
  }

  public static Object propertyMacro_GetPropertyValue_8766321956511159769(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SNodeOperations.getAncestor(_context.getNode(), "NewLanguage.structure.State", false, false), "name");
  }

  public static Object propertyMacro_GetPropertyValue_8766321956511159792(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), "actuator", false), "type");
  }

  public static Object propertyMacro_GetPropertyValue_8766321956511159811(final PropertyMacroContext _context) {
    if (SPropertyOperations.hasValue(_context.getNode(), "nextActuatorState", "1", "0")) {
      return "HIGH_STATE";
    }
    return "LOW_STATE";
  }

  public static Object propertyMacro_GetPropertyValue_8766321956511905755(final PropertyMacroContext _context) {
    return SPropertyOperations.getInteger(_context.getNode(), "delay") + "";
  }

  public static Object propertyMacro_GetPropertyValue_8766321956511219576(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), "name");
  }

  public static Object propertyMacro_GetPropertyValue_8766321956511176284(final PropertyMacroContext _context) {
    return _context.createUniqueName("transition_", null);
  }

  public static Object propertyMacro_GetPropertyValue_8766321956511176312(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), "nextStateRef", false), "name");
  }

  public static Object propertyMacro_GetPropertyValue_8766321956511176341(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), "actuatorRef", false), "type");
  }

  public static Object propertyMacro_GetPropertyValue_8766321956511176358(final PropertyMacroContext _context) {
    if (SPropertyOperations.hasValue(_context.getNode(), "actuatorState", "1", "0")) {
      return "HIGH_STATE";
    }
    return "LOW_STATE";
  }

  public static Object propertyMacro_GetPropertyValue_8766321956512928122(final PropertyMacroContext _context) {
    return SNodeOperations.getIndexInParent(SLinkOperations.getTarget(_context.getNode(), "konami", true)) != -1;
  }

  public static Object propertyMacro_GetPropertyValue_8766321956509475560(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), "konami", true), "joystick", false), "type");
  }

  public static Object propertyMacro_GetPropertyValue_8766321956509513289(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), "konami", true), "ledB", false), "type");
  }

  public static Object propertyMacro_GetPropertyValue_8766321956509492922(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), "konami", true), "ledA", false), "type");
  }

  public static Object propertyMacro_GetPropertyValue_8766321956509528000(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), "konami", true), "buzzer", false), "type");
  }

  public static Object propertyMacro_GetPropertyValue_8766321956509547363(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), "konami", true), "command");
  }

  public static Object propertyMacro_GetPropertyValue_8766321956514586950(final PropertyMacroContext _context) {
    return SNodeOperations.getIndexInParent(_context.getNode()) == 0.0;
  }

  public static Object propertyMacro_GetPropertyValue_8766321956515704903(final PropertyMacroContext _context) {
    return SNodeOperations.getIndexInParent(_context.getNode()) + "";
  }

  public static Object propertyMacro_GetPropertyValue_8766321956514628444(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), "name");
  }

  public static Object propertyMacro_GetPropertyValue_8766321956514741587(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), "name");
  }

  public static Iterable<SNode> sourceNodesQuery_3334193164822791532(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getTargets(_context.getNode(), "actuators", true);
  }

  public static Iterable<SNode> sourceNodesQuery_6096292100219473138(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getTargets(_context.getNode(), "smodelAttribute", true);
  }

  public static Iterable<SNode> sourceNodesQuery_8766321956508593821(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getTargets(_context.getNode(), "actuator", true);
  }

  public static Iterable<SNode> sourceNodesQuery_8766321956509256380(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getTargets(_context.getNode(), "actuator", true);
  }

  public static Iterable<SNode> sourceNodesQuery_8766321956511159825(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getTargets(_context.getNode(), "action", true);
  }

  public static Iterable<SNode> sourceNodesQuery_8766321956511159832(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getTargets(_context.getNode(), "state", true);
  }

  public static Iterable<SNode> sourceNodesQuery_8766321956511176372(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getTargets(_context.getNode(), "conditions", true);
  }

  public static Iterable<SNode> sourceNodesQuery_8766321956511176413(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getTargets(_context.getNode(), "transitions", true);
  }

  public static Iterable<SNode> sourceNodesQuery_8766321956511176420(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getTargets(_context.getNode(), "state", true);
  }

  public static Iterable<SNode> sourceNodesQuery_8766321956514585896(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getTargets(_context.getNode(), "state", true);
  }
}
