package konami;

/*Generated by MPS */


public class ArduinoBoardGenerator {


  public static void main(String[] args) {

    System.out.println("#include <ArduinoML.h>\n");

    System.out.print("arduino_ml::ArduinoBoard board");
    Boolean freqDefined = false;
    if (freqDefined) {
      System.out.print("(");
      System.out.print("0");
      System.out.print(")");
    }
    if (!(freqDefined)) {
      // <node> 
    }
    System.out.println(";");

    // <node> 


    // on genere le konami code ici 
    // ...konami 
    System.out.println("void setup(){");
    System.out.print("\tarduino_ml::");
    System.out.print("Led");
    System.out.print("* ");
    System.out.print("led_rouge");
    System.out.print(" = new arduino_ml::");
    System.out.print("Led");
    System.out.print("(\"");
    System.out.print("led_rouge");
    System.out.print("\",");
    System.out.print("10");
    if (false) {
      // <node> 
      System.out.print(",");
      System.out.print("");
      System.out.print(",");
      System.out.print("");
      // <node> 
    }
    System.out.println(");");
    System.out.print("\tarduino_ml::");
    System.out.print("Led");
    System.out.print("* ");
    System.out.print("led_verte");
    System.out.print(" = new arduino_ml::");
    System.out.print("Led");
    System.out.print("(\"");
    System.out.print("led_verte");
    System.out.print("\",");
    System.out.print("11");
    if (false) {
      // <node> 
      System.out.print(",");
      System.out.print("");
      System.out.print(",");
      System.out.print("");
      // <node> 
    }
    System.out.println(");");
    System.out.print("\tarduino_ml::");
    System.out.print("Buzzer");
    System.out.print("* ");
    System.out.print("buzzer");
    System.out.print(" = new arduino_ml::");
    System.out.print("Buzzer");
    System.out.print("(\"");
    System.out.print("buzzer");
    System.out.print("\",");
    System.out.print("12");
    if (false) {
      // <node> 
      System.out.print(",");
      System.out.print("");
      System.out.print(",");
      System.out.print("");
      // <node> 
    }
    System.out.println(");");
    System.out.print("\tarduino_ml::");
    System.out.print("Joystick");
    System.out.print("* ");
    System.out.print("joystick");
    System.out.print(" = new arduino_ml::");
    System.out.print("Joystick");
    System.out.print("(\"");
    System.out.print("joystick");
    System.out.print("\",");
    System.out.print("10");
    if (true) {
      // <node> 
      System.out.print(",");
      System.out.print("2");
      System.out.print(",");
      System.out.print("1");
      // <node> 
    }
    System.out.println(");");

    System.out.println("");

    System.out.print("\tboard.add_actuator(");
    System.out.print("led_rouge");
    System.out.println(");");
    System.out.print("\tboard.add_actuator(");
    System.out.print("led_verte");
    System.out.println(");");
    System.out.print("\tboard.add_actuator(");
    System.out.print("buzzer");
    System.out.println(");");
    System.out.print("\tboard.add_actuator(");
    System.out.print("joystick");
    System.out.println(");");

    System.out.println("");

    // freq quand faut t-il le mettre? 
    // <node> 

    // crée les états et les initialises avec les actions adequates 

    // cree les transitions et y ajoute les conditions 

    Boolean existKonami = true;
    if (existKonami) {
      // creation de l objet konami 
      System.out.print("\tarduino_ml::Konami* konami = new arduino_ml::Konami(");
      System.out.print("joystick");
      System.out.print(",");
      System.out.print("led_verte");
      System.out.print(",");
      System.out.print("led_rouge");
      System.out.print(",");
      System.out.print("buzzer");
      System.out.print(",");
      System.out.print("\"");
      System.out.print("UP DOWN RIGHT LEFT");
      System.out.println("\");");
    }

    System.out.println("\tboard.init_pins();");

    if (existKonami) {
      System.out.println("\tboard.init(konami->init_state());");
    }
    if (!(existKonami)) {
    }
    System.out.println("}");

    System.out.println("void loop(){");
    System.out.println("\tboard.iteration();");
    System.out.println("}");
  }
}
