package NewLanguage.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public abstract class Actuator_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public Actuator_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "NewLanguage.structure.Actuator";
  }
}
