package NewLanguage.behavior;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BehaviorDescriptor;
import java.util.Arrays;
import jetbrains.mps.smodel.runtime.interpreted.BehaviorAspectInterpreted;

public class BehaviorAspectDescriptor implements jetbrains.mps.smodel.runtime.BehaviorAspectDescriptor {
  public BehaviorAspectDescriptor() {
  }

  public BehaviorDescriptor getDescriptor(String fqName) {
    switch (Arrays.binarySearch(stringSwitchCases_846f5o_a0a0b, fqName)) {
      case 1:
        return new ArduinoBoard_BehaviorDescriptor();
      case 7:
        return new State_BehaviorDescriptor();
      case 8:
        return new Transition_BehaviorDescriptor();
      case 0:
        return new Action_BehaviorDescriptor();
      case 4:
        return new Condition_BehaviorDescriptor();
      case 2:
        return new Button_BehaviorDescriptor();
      case 10:
        return new macro_BehaviorDescriptor();
      case 11:
        return new macro2_BehaviorDescriptor();
      case 9:
        return new konami_BehaviorDescriptor();
      case 6:
        return new Led_BehaviorDescriptor();
      case 3:
        return new Buzzer_BehaviorDescriptor();
      case 5:
        return new Joystick_BehaviorDescriptor();
      default:
        return BehaviorAspectInterpreted.getInstance().getDescriptor(fqName);
    }
  }

  private static String[] stringSwitchCases_846f5o_a0a0b = new String[]{"NewLanguage.structure.Action", "NewLanguage.structure.ArduinoBoard", "NewLanguage.structure.Button", "NewLanguage.structure.Buzzer", "NewLanguage.structure.Condition", "NewLanguage.structure.Joystick", "NewLanguage.structure.Led", "NewLanguage.structure.State", "NewLanguage.structure.Transition", "NewLanguage.structure.konami", "NewLanguage.structure.macro", "NewLanguage.structure.macro2"};
}
