package NewLanguage.behavior;

/*Generated by MPS */


public class Button_BehaviorDescriptor extends Actuator_BehaviorDescriptor {
  public Button_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "NewLanguage.structure.Button";
  }
}
