package NewLanguage.behavior;

/*Generated by MPS */


public class Buzzer_BehaviorDescriptor extends Actuator_BehaviorDescriptor {
  public Buzzer_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "NewLanguage.structure.Buzzer";
  }
}
