package NewLanguage.behavior;

/*Generated by MPS */


public class Joystick_BehaviorDescriptor extends Actuator_BehaviorDescriptor {
  public Joystick_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "NewLanguage.structure.Joystick";
  }
}
