package NewLanguage.behavior;

/*Generated by MPS */


public class Led_BehaviorDescriptor extends Actuator_BehaviorDescriptor {
  public Led_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "NewLanguage.structure.Led";
  }
}
