package NewLanguage.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class macro2_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public macro2_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "NewLanguage.structure.macro2";
  }
}
