package NewLanguage.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class State_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public State_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "NewLanguage.structure.State";
  }
}
