package frequency;

/*Generated by MPS */


public class ArduinoBoardGenerator {


  public static void main(String[] args) {

    System.out.println("#include <ArduinoML.h>\n");

    System.out.print("arduino_ml::ArduinoBoard board");
    Boolean freqDefined = true;
    if (freqDefined) {
      System.out.print("(");
      System.out.print("0.5");
      System.out.print(")");
    }
    if (!(freqDefined)) {
      // <node> 
    }
    System.out.println(";");

    // <node> 


    // on genere le konami code ici 
    // ...konami 
    System.out.println("void setup(){");
    System.out.print("\tarduino_ml::");
    System.out.print("Led");
    System.out.print("* ");
    System.out.print("led");
    System.out.print(" = new arduino_ml::");
    System.out.print("Led");
    System.out.print("(\"");
    System.out.print("led");
    System.out.print("\",");
    System.out.print("11");
    if (false) {
      // <node> 
      System.out.print(",");
      System.out.print("");
      System.out.print(",");
      System.out.print("");
      // <node> 
    }
    System.out.println(");");

    System.out.println("");

    System.out.print("\tboard.add_actuator(");
    System.out.print("led");
    System.out.println(");");

    System.out.println("");

    // freq quand faut t-il le mettre? 
    // <node> 

    // crée les états et les initialises avec les actions adequates 
    System.out.print("\tarduino_ml::State* ");
    System.out.print("initialFreq");
    System.out.print(" = new arduino_ml::State(");
    System.out.print("true");
    System.out.println(");");
    System.out.print("\t");
    System.out.print("initialFreq");
    System.out.print("->add_action(");
    // TODO ajouter targer dans editor action 
    System.out.print("led");
    System.out.print(",arduino_ml::");
    System.out.print("LOW_STATE");
    System.out.print(",");
    System.out.print("200");
    System.out.println(");");
    System.out.print("\t");
    System.out.print("initialFreq");
    System.out.print("->add_action(");
    // TODO ajouter targer dans editor action 
    System.out.print("led");
    System.out.print(",arduino_ml::");
    System.out.print("HIGH_STATE");
    System.out.print(",");
    System.out.print("200");
    System.out.println(");");
    System.out.print("\t");
    System.out.print("initialFreq");
    System.out.print("->add_action(");
    // TODO ajouter targer dans editor action 
    System.out.print("led");
    System.out.print(",arduino_ml::");
    System.out.print("LOW_STATE");
    System.out.print(",");
    System.out.print("200");
    System.out.println(");");
    System.out.print("\t");
    System.out.print("initialFreq");
    System.out.print("->add_action(");
    // TODO ajouter targer dans editor action 
    System.out.print("led");
    System.out.print(",arduino_ml::");
    System.out.print("HIGH_STATE");
    System.out.print(",");
    System.out.print("200");
    System.out.println(");");
    System.out.println("");

    // cree les transitions et y ajoute les conditions 
    {
      String stateName = "initialFreq";
      System.out.println("");
    }

    Boolean existKonami = false;
    if (existKonami) {
      // creation de l objet konami 
      System.out.print("\tarduino_ml::Konami* konami = new arduino_ml::Konami(");
      System.out.print("");
      System.out.print(",");
      System.out.print("");
      System.out.print(",");
      System.out.print("");
      System.out.print(",");
      System.out.print("");
      System.out.print(",");
      System.out.print("\"");
      System.out.print("");
      System.out.println("\");");
    }

    System.out.println("\tboard.init_pins();");

    if (existKonami) {
      System.out.println("\tboard.init(konami->init_state());");
    }
    if (!(existKonami)) {
      {
        Boolean firstDefined = true;
        // <node> 

        if (firstDefined) {
          String initialState = "initialFreq";
          System.out.print("\tboard.init(");
          System.out.print("initialFreq");
          System.out.println(");");
        }
      }
    }
    System.out.println("}");

    System.out.println("void loop(){");
    System.out.println("\tboard.iteration();");
    System.out.println("}");
  }
}
